import type { Config } from "tailwindcss";
import defaultTheme from "tailwindcss/defaultTheme";
import twAnimate from "tailwindcss-animate";

export const preset: Partial<Config> = {
  darkMode: "selector",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        primary: {
          DEFAULT: "var(--primary-100)",
          100: "var(--primary-100)",
          200: "var(--primary-200)",
          300: "var(--primary-300)",
          400: "var(--primary-400)",
          500: "var(--primary-500)",
          600: "var(--primary-600)",
          700: "var(--primary-700)",
          800: "var(--primary-800)",
          900: "var(--primary-900)",
        },
        secondary: {
          DEFAULT: "var(--secondary-100)",
          100: "var(--secondary-100)",
          200: "var(--secondary-200)",
          300: "var(--secondary-300)",
          400: "var(--secondary-400)",
          500: "var(--secondary-500)",
          600: "var(--secondary-600)",
          700: "var(--secondary-700)",
          800: "var(--secondary-800)",
          900: "var(--secondary-900)",
        },
        tertiary: {
          DEFAULT: "var(--tertiary-100)",
          100: "var(--tertiary-100)",
          200: "var(--tertiary-200)",
          300: "var(--tertiary-300)",
          400: "var(--tertiary-400)",
          500: "var(--tertiary-500)",
          600: "var(--tertiary-600)",
          700: "var(--tertiary-700)",
          800: "var(--tertiary-800)",
          900: "var(--tertiary-900)",
        },
        white: {
          DEFAULT: "var(--white-100)",
          100: "var(--white-100)",
          200: "var(--white-200)",
          300: "var(--white-300)",
          400: "var(--white-400)",
          500: "var(--white-500)",
          600: "var(--white-600)",
          700: "var(--white-700)",
          800: "var(--white-800)",
          900: "var(--white-900)",
        },
        black: {
          DEFAULT: "var(--black-100)",
          100: "var(--black-100)",
          200: "var(--black-200)",
          300: "var(--black-300)",
          400: "var(--black-400)",
          500: "var(--black-500)",
          600: "var(--black-600)",
          700: "var(--black-700)",
          800: "var(--black-800)",
          900: "var(--black-900)",
        },
        green: {
          DEFAULT: "var(--green-100)",
          100: "var(--green-100)",
          200: "var(--green-200)",
          300: "var(--green-300)",
          400: "var(--green-400)",
          500: "var(--green-500)",
          600: "var(--green-600)",
          700: "var(--green-700)",
          800: "var(--green-800)",
          900: "var(--green-900)",
        },
        forest: {
          DEFAULT: "var(--forest-100)",
          100: "var(--forest-100)",
          200: "var(--forest-200)",
          300: "var(--forest-300)",
          400: "var(--forest-400)",
          500: "var(--forest-500)",
          600: "var(--forest-600)",
          700: "var(--forest-700)",
          800: "var(--forest-800)",
          900: "var(--forest-900)",
        },
        blue: {
          DEFAULT: "var(--blue-100)",
          100: "var(--blue-100)",
          200: "var(--blue-200)",
          300: "var(--blue-300)",
          400: "var(--blue-400)",
          500: "var(--blue-500)",
          600: "var(--blue-600)",
          700: "var(--blue-700)",
          800: "var(--blue-800)",
          900: "var(--blue-900)",
        },
        yellow: {
          DEFAULT: "var(--yellow-100)",
          100: "var(--yellow-100)",
          200: "var(--yellow-200)",
          300: "var(--yellow-300)",
          400: "var(--yellow-400)",
          500: "var(--yellow-500)",
          600: "var(--yellow-600)",
          700: "var(--yellow-700)",
          800: "var(--yellow-800)",
          900: "var(--yellow-900)",
        },
        orange: {
          DEFAULT: "var(--orange-100)",
          100: "var(--orange-100)",
          200: "var(--orange-200)",
          300: "var(--orange-300)",
          400: "var(--orange-400)",
          500: "var(--orange-500)",
          600: "var(--orange-600)",
          700: "var(--orange-700)",
          800: "var(--orange-800)",
          900: "var(--orange-900)",
        },
        salmon: {
          DEFAULT: "var(--salmon-100)",
          100: "var(--salmon-100)",
          200: "var(--salmon-200)",
          300: "var(--salmon-300)",
          400: "var(--salmon-400)",
          500: "var(--salmon-500)",
          600: "var(--salmon-600)",
          700: "var(--salmon-700)",
          800: "var(--salmon-800)",
          900: "var(--salmon-900)",
        },
        red: {
          DEFAULT: "var(--red-100)",
          100: "var(--red-100)",
          200: "var(--red-200)",
          300: "var(--red-300)",
          400: "var(--red-400)",
          500: "var(--red-500)",
          600: "var(--red-600)",
          700: "var(--red-700)",
          800: "var(--red-800)",
          900: "var(--red-900)",
        },
        purple: {
          DEFAULT: "var(--purple-100)",
          100: "var(--purple-100)",
          200: "var(--purple-200)",
          300: "var(--purple-300)",
          400: "var(--purple-400)",
          500: "var(--purple-500)",
          600: "var(--purple-600)",
          700: "var(--purple-700)",
          800: "var(--purple-800)",
          900: "var(--purple-900)",
        },
        "orb-multiplier": {
          DEFAULT: "var(--orb-multiplier)",
          faded: "var(--orb-multiplier-faded)",
        },
        "orb-chips": {
          DEFAULT: "var(--orb-chips)",
          faded: "var(--orb-chips-faded)",
        },
        "orb-heart": {
          DEFAULT: "var(--orb-heart)",
          faded: "var(--orb-heart-faded)",
        },
        "orb-moonrock": {
          DEFAULT: "var(--orb-moonrock)",
          faded: "var(--orb-moonrock-faded)",
        },
      },
      backgroundImage: {
        "green-gradient-100": "var(--green-gradient-100)",
        "orange-gradient-100": "var(--orange-gradient-100)",
        "red-gradient-100": "var(--red-gradient-100)",
        "multiplier-one-100": "var(--multiplier-one-100)",
        "multiplier-one-200": "var(--multiplier-one-200)",
        "multiplier-two-100": "var(--multiplier-two-100)",
        "multiplier-two-200": "var(--multiplier-two-200)",
        "multiplier-three-100": "var(--multiplier-three-100)",
        "multiplier-three-200": "var(--multiplier-three-200)",
        "multiplier-four-100": "var(--multiplier-four-100)",
        "multiplier-four-200": "var(--multiplier-four-200)",
        "multiplier-five-100": "var(--multiplier-five-100)",
        "multiplier-five-200": "var(--multiplier-five-200)",
        "point-gradient-100": "var(--point-gradient-100)",
        "multiplier-gradient-100": "var(--multiplier-gradient-100)",
        "hp-gradient-100": "var(--hp-gradient-100)",
        "moonrock-gradient-100": "var(--moonrock-gradient-100)",
        "chip-gradient-100": "var(--chip-gradient-100)",
      },
      fontFamily: {
        inherit: "inherit",
        body: ["Rubik One", "sans"],
        glitch: ["Rubik Glitch", "sans"],
        primary: ["Rubik One", "sans"],
        secondary: ["VT323", "sans"],
        sans: ["Inter", ...defaultTheme.fontFamily.sans],
        mono: ["IBM Plex Mono", ...defaultTheme.fontFamily.mono],
      },
      fontSize: {
        "2xs": "10px",
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 6px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        shimmer: {
          "0%": { backgroundPosition: "100% 0" },
          "20%": { backgroundPosition: "-100% 0" },
          "100%": { backgroundPosition: "-100% 0" },
        },
        "font-glitch": {
          "0%": {
            fontFamily: "inherit",
            letterSpacing: "inherit",
            transform: "translateY(0)",
            wordSpacing: "inherit",
          },
          "1.5%": {
            fontFamily: "Rubik Glitch, sans",
            letterSpacing: "0.03em",
            transform: "translateY(-0.04em)",
            wordSpacing: "0.05em",
          },
          "3%": {
            fontFamily: "inherit",
            letterSpacing: "inherit",
            transform: "translateY(0)",
            wordSpacing: "inherit",
          },
          "42%": {
            fontFamily: "Rubik Glitch, sans",
            letterSpacing: "0.03em",
            transform: "translateY(-0.04em)",
            wordSpacing: "0.05em",
          },
          "44%": {
            fontFamily: "inherit",
            letterSpacing: "inherit",
            transform: "translateY(0)",
            wordSpacing: "inherit",
          },
          "65.5%": {
            fontFamily: "Rubik Glitch, sans",
            letterSpacing: "0.03em",
            transform: "translateY(-0.04em)",
            wordSpacing: "0.05em",
          },
          "66.5%": {
            fontFamily: "inherit",
            letterSpacing: "inherit",
            transform: "translateY(0)",
            wordSpacing: "inherit",
          },
          "92.5%": {
            fontFamily: "Rubik Glitch, sans",
            letterSpacing: "0.03em",
            transform: "translateY(-0.04em)",
            wordSpacing: "0.05em",
          },
          "93%": {
            fontFamily: "inherit",
            letterSpacing: "inherit",
            transform: "translateY(0)",
            wordSpacing: "inherit",
          },
          "100%": {
            fontFamily: "inherit",
            letterSpacing: "inherit",
            transform: "translateY(0)",
            wordSpacing: "inherit",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        shimmer: "shimmer 2s linear infinite",
        glitch: "font-glitch 5s step-end infinite",
      },
    },
  },
  plugins: [twAnimate],
};
