packages:
  - "client"
  - "contracts/tokens"
catalog:
  "@cartridge/connector": "0.11.3"
  "@cartridge/controller": "0.11.3"
  "@dojoengine/core": "1.8.5"
  "@dojoengine/sdk": "1.8.7"
  "@dojoengine/torii-wasm": "1.8.1"
  "@dojoengine/utils": "1.8.1"
