world_address = "0x0406ad504e4aff4a66c0e35132b6d1659c066804e7bb5ff38523ea3417406ebd"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
world_block = 0
controllers = true
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

[http]
cors_origins = ["*"]

[erc]
metadata_updates = true
