world_address = "0x06e93be73d7980ad655b7e019148074edcb75e524b187a8b7997595ea16e2c93"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
world_block = 0
controllers = true
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

[http]
cors_origins = ["*"]

[sql]
historical = [
  "GLITCHBOMB-TrophyProgression",
  "GLITCHBOMB-QuestProgression",
  "GLITCHBOMB-BundleIssued",
]

[erc]
metadata_updates = true
