world_address = "0x0101dee50298835d55cc60a83db6f6036ec2186144e1a36d37e771796d9855c4"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
debug = true
world_block = 0
controllers = true
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

[sql]
historical = [
  "GLITCHBOMB-TrophyProgression",
  "GLITCHBOMB-QuestProgression",
  "GLITCHBOMB-BundleIssued",
]

[erc]
metadata_updates = true
