// External imports

use achievement::types::task::{Task as AchievementTask, TaskTrait as AchievementTaskTrait};

// Internal imports

use crate::elements::tasks;

// Types

#[derive(Copy, Drop, PartialEq)]
pub enum Task {
    None,
    // Conqueror
    Conqueror,
    Flawless,
    LevelCritical,
    LevelFlawless,
    NeverSurrender,
    WhatBombs,
    // Scorer
    Bottomless,
    Bottomless15,
    Bottomless25,
    Bottomless30,
    Bottomless40,
    LevelScorer35,
    LevelScorer45,
    LevelScorer60,
    QuickFinish3,
    QuickFinish4,
    Surge,
    Overload,
    Surge20,
    // Multiplier
    Climber3,
    Climber4,
    Climber5,
    SkyHigh,
    ToTheMoon,
    // Shopper
    DiamondHands,
    ShopRich80,
    Shopper6,
    Shopper10,
    Shopper15,
    Specialist,
    Spender,
    // Moonrock
    CashOut125,
    CashOut135,
    CashOut150,
    CashOut160,
    CashOut180,
    CashOut200,
    CashOut300,
    CashOut400,
    CashOut500,
    CashOut600,
    CashOut700,
    Harvest,
    Harvest5,
    Harvest40,
    Harvest80,
    Jackpot,
    Lunarian,
    Moonshot,
    LunarEclipse,
    Supernova,
    InfiniteGlitch,
    Survivor1,
    Survivor2,
    // Composer
    Linear,
    Exponential,
    Metagamer,
    Medic,
    Immortal,
    Immortal5,
    // Sequencer
    Armageddon3,
    Armageddon4,
    BombStreak3,
    BombStreak4,
    BombStreak5,
    FullyTorqued,
    GameBombs10,
    GameBombs15,
    // Brinker
    Defused,
    Flatline,
    WhatNow,
    // Loyalty
    Loyalty,
    // Level
    LevelReacher2,
    LevelReacher3,
    LevelReacher4,
    LevelReacher5,
    LevelReacher6,
    // Bag
    BagCopies4,
    BagCopies5,
    BagCopies6,
    BagSize20,
    BagSize25,
    // Puller
    BombPuller,
    HealthPuller,
    MultiplierPuller,
    OrbPuller,
    PointsPuller,
    SpecialPuller,
}

// Implementations

#[generate_trait]
pub impl TaskImpl of TaskTrait {
    fn identifier(self: Task) -> felt252 {
        match self {
            Task::None => 0,
            Task::Conqueror => tasks::conqueror::Conqueror::identifier(),
            Task::Flawless => tasks::conqueror::Flawless::identifier(),
            Task::LevelCritical => tasks::conqueror::LevelCritical::identifier(),
            Task::LevelFlawless => tasks::conqueror::LevelFlawless::identifier(),
            Task::NeverSurrender => tasks::conqueror::NeverSurrender::identifier(),
            Task::WhatBombs => tasks::conqueror::WhatBombs::identifier(),
            Task::Bottomless => tasks::scorer::Bottomless::identifier(),
            Task::Bottomless15 => tasks::scorer::Bottomless15::identifier(),
            Task::Bottomless25 => tasks::scorer::Bottomless25::identifier(),
            Task::Bottomless30 => tasks::scorer::Bottomless30::identifier(),
            Task::Bottomless40 => tasks::scorer::Bottomless40::identifier(),
            Task::LevelScorer35 => tasks::scorer::LevelScorer35::identifier(),
            Task::LevelScorer45 => tasks::scorer::LevelScorer45::identifier(),
            Task::LevelScorer60 => tasks::scorer::LevelScorer60::identifier(),
            Task::QuickFinish3 => tasks::scorer::QuickFinish3::identifier(),
            Task::QuickFinish4 => tasks::scorer::QuickFinish4::identifier(),
            Task::Surge => tasks::scorer::Surge::identifier(),
            Task::Overload => tasks::scorer::Overload::identifier(),
            Task::Surge20 => tasks::scorer::Surge20::identifier(),
            Task::Climber3 => tasks::multiplier::Climber3::identifier(),
            Task::Climber4 => tasks::multiplier::Climber4::identifier(),
            Task::Climber5 => tasks::multiplier::Climber5::identifier(),
            Task::SkyHigh => tasks::multiplier::SkyHigh::identifier(),
            Task::ToTheMoon => tasks::multiplier::ToTheMoon::identifier(),
            Task::DiamondHands => tasks::shopper::DiamondHands::identifier(),
            Task::ShopRich80 => tasks::shopper::ShopRich80::identifier(),
            Task::Shopper6 => tasks::shopper::Shopper6::identifier(),
            Task::Shopper10 => tasks::shopper::Shopper10::identifier(),
            Task::Shopper15 => tasks::shopper::Shopper15::identifier(),
            Task::Specialist => tasks::shopper::Specialist::identifier(),
            Task::Spender => tasks::shopper::Spender::identifier(),
            Task::CashOut125 => tasks::moonrock::CashOut125::identifier(),
            Task::CashOut135 => tasks::moonrock::CashOut135::identifier(),
            Task::CashOut150 => tasks::moonrock::CashOut150::identifier(),
            Task::CashOut160 => tasks::moonrock::CashOut160::identifier(),
            Task::CashOut180 => tasks::moonrock::CashOut180::identifier(),
            Task::CashOut200 => tasks::moonrock::CashOut200::identifier(),
            Task::CashOut300 => tasks::moonrock::CashOut300::identifier(),
            Task::CashOut400 => tasks::moonrock::CashOut400::identifier(),
            Task::CashOut500 => tasks::moonrock::CashOut500::identifier(),
            Task::CashOut600 => tasks::moonrock::CashOut600::identifier(),
            Task::CashOut700 => tasks::moonrock::CashOut700::identifier(),
            Task::Harvest => tasks::moonrock::Harvest::identifier(),
            Task::Harvest5 => tasks::moonrock::Harvest5::identifier(),
            Task::Harvest40 => tasks::moonrock::Harvest40::identifier(),
            Task::Harvest80 => tasks::moonrock::Harvest80::identifier(),
            Task::Jackpot => tasks::moonrock::Jackpot::identifier(),
            Task::Lunarian => tasks::moonrock::Lunarian::identifier(),
            Task::Moonshot => tasks::moonrock::Moonshot::identifier(),
            Task::LunarEclipse => tasks::moonrock::LunarEclipse::identifier(),
            Task::Supernova => tasks::moonrock::Supernova::identifier(),
            Task::InfiniteGlitch => tasks::moonrock::InfiniteGlitch::identifier(),
            Task::Survivor1 => tasks::moonrock::Survivor1::identifier(),
            Task::Survivor2 => tasks::moonrock::Survivor2::identifier(),
            Task::Linear => tasks::composer::Linear::identifier(),
            Task::Exponential => tasks::composer::Exponential::identifier(),
            Task::Metagamer => tasks::composer::Metagamer::identifier(),
            Task::Medic => tasks::composer::Medic::identifier(),
            Task::Immortal => tasks::composer::Immortal::identifier(),
            Task::Immortal5 => tasks::composer::Immortal5::identifier(),
            Task::Armageddon3 => tasks::sequencer::Armageddon3::identifier(),
            Task::Armageddon4 => tasks::sequencer::Armageddon4::identifier(),
            Task::BombStreak3 => tasks::sequencer::BombStreak3::identifier(),
            Task::BombStreak4 => tasks::sequencer::BombStreak4::identifier(),
            Task::BombStreak5 => tasks::sequencer::BombStreak5::identifier(),
            Task::FullyTorqued => tasks::sequencer::FullyTorqued::identifier(),
            Task::GameBombs10 => tasks::sequencer::GameBombs10::identifier(),
            Task::GameBombs15 => tasks::sequencer::GameBombs15::identifier(),
            Task::Defused => tasks::brinker::Defused::identifier(),
            Task::Flatline => tasks::brinker::Flatline::identifier(),
            Task::WhatNow => tasks::brinker::WhatNow::identifier(),
            Task::Loyalty => tasks::loyalty::Loyalty::identifier(),
            Task::LevelReacher2 => tasks::level::LevelReacher2::identifier(),
            Task::LevelReacher3 => tasks::level::LevelReacher3::identifier(),
            Task::LevelReacher4 => tasks::level::LevelReacher4::identifier(),
            Task::LevelReacher5 => tasks::level::LevelReacher5::identifier(),
            Task::LevelReacher6 => tasks::level::LevelReacher6::identifier(),
            Task::BagCopies4 => tasks::bag::BagCopies4::identifier(),
            Task::BagCopies5 => tasks::bag::BagCopies5::identifier(),
            Task::BagCopies6 => tasks::bag::BagCopies6::identifier(),
            Task::BagSize20 => tasks::bag::BagSize20::identifier(),
            Task::BagSize25 => tasks::bag::BagSize25::identifier(),
            Task::BombPuller => tasks::puller::BombPuller::identifier(),
            Task::HealthPuller => tasks::puller::HealthPuller::identifier(),
            Task::MultiplierPuller => tasks::puller::MultiplierPuller::identifier(),
            Task::OrbPuller => tasks::puller::OrbPuller::identifier(),
            Task::PointsPuller => tasks::puller::PointsPuller::identifier(),
            Task::SpecialPuller => tasks::puller::SpecialPuller::identifier(),
        }
    }

    fn description(self: Task, count: u32) -> ByteArray {
        match self {
            Task::None => "",
            Task::Conqueror => tasks::conqueror::Conqueror::description(count),
            Task::Flawless => tasks::conqueror::Flawless::description(count),
            Task::LevelCritical => tasks::conqueror::LevelCritical::description(count),
            Task::LevelFlawless => tasks::conqueror::LevelFlawless::description(count),
            Task::NeverSurrender => tasks::conqueror::NeverSurrender::description(count),
            Task::WhatBombs => tasks::conqueror::WhatBombs::description(count),
            Task::Bottomless => tasks::scorer::Bottomless::description(count),
            Task::Bottomless15 => tasks::scorer::Bottomless15::description(count),
            Task::Bottomless25 => tasks::scorer::Bottomless25::description(count),
            Task::Bottomless30 => tasks::scorer::Bottomless30::description(count),
            Task::Bottomless40 => tasks::scorer::Bottomless40::description(count),
            Task::LevelScorer35 => tasks::scorer::LevelScorer35::description(count),
            Task::LevelScorer45 => tasks::scorer::LevelScorer45::description(count),
            Task::LevelScorer60 => tasks::scorer::LevelScorer60::description(count),
            Task::QuickFinish3 => tasks::scorer::QuickFinish3::description(count),
            Task::QuickFinish4 => tasks::scorer::QuickFinish4::description(count),
            Task::Surge => tasks::scorer::Surge::description(count),
            Task::Overload => tasks::scorer::Overload::description(count),
            Task::Surge20 => tasks::scorer::Surge20::description(count),
            Task::Climber3 => tasks::multiplier::Climber3::description(count),
            Task::Climber4 => tasks::multiplier::Climber4::description(count),
            Task::Climber5 => tasks::multiplier::Climber5::description(count),
            Task::SkyHigh => tasks::multiplier::SkyHigh::description(count),
            Task::ToTheMoon => tasks::multiplier::ToTheMoon::description(count),
            Task::DiamondHands => tasks::shopper::DiamondHands::description(count),
            Task::ShopRich80 => tasks::shopper::ShopRich80::description(count),
            Task::Shopper6 => tasks::shopper::Shopper6::description(count),
            Task::Shopper10 => tasks::shopper::Shopper10::description(count),
            Task::Shopper15 => tasks::shopper::Shopper15::description(count),
            Task::Specialist => tasks::shopper::Specialist::description(count),
            Task::Spender => tasks::shopper::Spender::description(count),
            Task::CashOut125 => tasks::moonrock::CashOut125::description(count),
            Task::CashOut135 => tasks::moonrock::CashOut135::description(count),
            Task::CashOut150 => tasks::moonrock::CashOut150::description(count),
            Task::CashOut160 => tasks::moonrock::CashOut160::description(count),
            Task::CashOut180 => tasks::moonrock::CashOut180::description(count),
            Task::CashOut200 => tasks::moonrock::CashOut200::description(count),
            Task::CashOut300 => tasks::moonrock::CashOut300::description(count),
            Task::CashOut400 => tasks::moonrock::CashOut400::description(count),
            Task::CashOut500 => tasks::moonrock::CashOut500::description(count),
            Task::CashOut600 => tasks::moonrock::CashOut600::description(count),
            Task::CashOut700 => tasks::moonrock::CashOut700::description(count),
            Task::Harvest => tasks::moonrock::Harvest::description(count),
            Task::Harvest5 => tasks::moonrock::Harvest5::description(count),
            Task::Harvest40 => tasks::moonrock::Harvest40::description(count),
            Task::Harvest80 => tasks::moonrock::Harvest80::description(count),
            Task::Jackpot => tasks::moonrock::Jackpot::description(count),
            Task::Lunarian => tasks::moonrock::Lunarian::description(count),
            Task::Moonshot => tasks::moonrock::Moonshot::description(count),
            Task::LunarEclipse => tasks::moonrock::LunarEclipse::description(count),
            Task::Supernova => tasks::moonrock::Supernova::description(count),
            Task::InfiniteGlitch => tasks::moonrock::InfiniteGlitch::description(count),
            Task::Survivor1 => tasks::moonrock::Survivor1::description(count),
            Task::Survivor2 => tasks::moonrock::Survivor2::description(count),
            Task::Linear => tasks::composer::Linear::description(count),
            Task::Exponential => tasks::composer::Exponential::description(count),
            Task::Metagamer => tasks::composer::Metagamer::description(count),
            Task::Medic => tasks::composer::Medic::description(count),
            Task::Immortal => tasks::composer::Immortal::description(count),
            Task::Immortal5 => tasks::composer::Immortal5::description(count),
            Task::Armageddon3 => tasks::sequencer::Armageddon3::description(count),
            Task::Armageddon4 => tasks::sequencer::Armageddon4::description(count),
            Task::BombStreak3 => tasks::sequencer::BombStreak3::description(count),
            Task::BombStreak4 => tasks::sequencer::BombStreak4::description(count),
            Task::BombStreak5 => tasks::sequencer::BombStreak5::description(count),
            Task::FullyTorqued => tasks::sequencer::FullyTorqued::description(count),
            Task::GameBombs10 => tasks::sequencer::GameBombs10::description(count),
            Task::GameBombs15 => tasks::sequencer::GameBombs15::description(count),
            Task::Defused => tasks::brinker::Defused::description(count),
            Task::Flatline => tasks::brinker::Flatline::description(count),
            Task::WhatNow => tasks::brinker::WhatNow::description(count),
            Task::Loyalty => tasks::loyalty::Loyalty::description(count),
            Task::LevelReacher2 => tasks::level::LevelReacher2::description(count),
            Task::LevelReacher3 => tasks::level::LevelReacher3::description(count),
            Task::LevelReacher4 => tasks::level::LevelReacher4::description(count),
            Task::LevelReacher5 => tasks::level::LevelReacher5::description(count),
            Task::LevelReacher6 => tasks::level::LevelReacher6::description(count),
            Task::BagCopies4 => tasks::bag::BagCopies4::description(count),
            Task::BagCopies5 => tasks::bag::BagCopies5::description(count),
            Task::BagCopies6 => tasks::bag::BagCopies6::description(count),
            Task::BagSize20 => tasks::bag::BagSize20::description(count),
            Task::BagSize25 => tasks::bag::BagSize25::description(count),
            Task::BombPuller => tasks::puller::BombPuller::description(count),
            Task::HealthPuller => tasks::puller::HealthPuller::description(count),
            Task::MultiplierPuller => tasks::puller::MultiplierPuller::description(count),
            Task::OrbPuller => tasks::puller::OrbPuller::description(count),
            Task::PointsPuller => tasks::puller::PointsPuller::description(count),
            Task::SpecialPuller => tasks::puller::SpecialPuller::description(count),
        }
    }

    fn tasks(self: Task, count: u32) -> Span<AchievementTask> {
        let task_id: felt252 = self.identifier();
        let description: ByteArray = self.description(count);
        array![AchievementTaskTrait::new(task_id, count.into(), description)].span()
    }
}

impl IntoTaskU8 of core::traits::Into<Task, u8> {
    fn into(self: Task) -> u8 {
        match self {
            Task::None => 0,
            Task::Conqueror => 1,
            Task::Flawless => 2,
            Task::LevelCritical => 3,
            Task::LevelFlawless => 4,
            Task::NeverSurrender => 5,
            Task::WhatBombs => 6,
            Task::Bottomless => 7,
            Task::Bottomless15 => 8,
            Task::Bottomless25 => 9,
            Task::Bottomless30 => 10,
            Task::Bottomless40 => 11,
            Task::LevelScorer35 => 12,
            Task::LevelScorer45 => 13,
            Task::LevelScorer60 => 14,
            Task::QuickFinish3 => 15,
            Task::QuickFinish4 => 16,
            Task::Surge => 17,
            Task::Overload => 18,
            Task::Surge20 => 19,
            Task::Climber3 => 20,
            Task::Climber4 => 21,
            Task::Climber5 => 22,
            Task::SkyHigh => 23,
            Task::ToTheMoon => 24,
            Task::DiamondHands => 25,
            Task::ShopRich80 => 26,
            Task::Shopper6 => 27,
            Task::Shopper10 => 28,
            Task::Shopper15 => 29,
            Task::Specialist => 30,
            Task::Spender => 31,
            Task::CashOut125 => 32,
            Task::CashOut135 => 33,
            Task::CashOut150 => 34,
            Task::CashOut160 => 35,
            Task::CashOut180 => 36,
            Task::CashOut200 => 37,
            Task::CashOut300 => 38,
            Task::CashOut400 => 39,
            Task::CashOut500 => 40,
            Task::CashOut600 => 41,
            Task::CashOut700 => 42,
            Task::Harvest => 43,
            Task::Harvest5 => 44,
            Task::Harvest40 => 45,
            Task::Harvest80 => 46,
            Task::Jackpot => 47,
            Task::Lunarian => 48,
            Task::Moonshot => 49,
            Task::LunarEclipse => 50,
            Task::Supernova => 51,
            Task::InfiniteGlitch => 52,
            Task::Survivor1 => 53,
            Task::Survivor2 => 54,
            Task::Linear => 55,
            Task::Exponential => 56,
            Task::Metagamer => 57,
            Task::Medic => 58,
            Task::Immortal => 59,
            Task::Immortal5 => 60,
            Task::Armageddon3 => 61,
            Task::Armageddon4 => 62,
            Task::BombStreak3 => 63,
            Task::BombStreak4 => 64,
            Task::BombStreak5 => 65,
            Task::FullyTorqued => 66,
            Task::GameBombs10 => 67,
            Task::GameBombs15 => 68,
            Task::Defused => 69,
            Task::Flatline => 70,
            Task::WhatNow => 71,
            Task::Loyalty => 72,
            Task::LevelReacher2 => 73,
            Task::LevelReacher3 => 74,
            Task::LevelReacher4 => 75,
            Task::LevelReacher5 => 76,
            Task::LevelReacher6 => 77,
            Task::BagCopies4 => 78,
            Task::BagCopies5 => 79,
            Task::BagCopies6 => 80,
            Task::BagSize20 => 81,
            Task::BagSize25 => 82,
            Task::BombPuller => 83,
            Task::HealthPuller => 84,
            Task::MultiplierPuller => 85,
            Task::OrbPuller => 86,
            Task::PointsPuller => 87,
            Task::SpecialPuller => 88,
        }
    }
}

impl IntoU8Task of core::traits::Into<u8, Task> {
    fn into(self: u8) -> Task {
        let card: felt252 = self.into();
        match card {
            0 => Task::None,
            1 => Task::Conqueror,
            2 => Task::Flawless,
            3 => Task::LevelCritical,
            4 => Task::LevelFlawless,
            5 => Task::NeverSurrender,
            6 => Task::WhatBombs,
            7 => Task::Bottomless,
            8 => Task::Bottomless15,
            9 => Task::Bottomless25,
            10 => Task::Bottomless30,
            11 => Task::Bottomless40,
            12 => Task::LevelScorer35,
            13 => Task::LevelScorer45,
            14 => Task::LevelScorer60,
            15 => Task::QuickFinish3,
            16 => Task::QuickFinish4,
            17 => Task::Surge,
            18 => Task::Overload,
            19 => Task::Surge20,
            20 => Task::Climber3,
            21 => Task::Climber4,
            22 => Task::Climber5,
            23 => Task::SkyHigh,
            24 => Task::ToTheMoon,
            25 => Task::DiamondHands,
            26 => Task::ShopRich80,
            27 => Task::Shopper6,
            28 => Task::Shopper10,
            29 => Task::Shopper15,
            30 => Task::Specialist,
            31 => Task::Spender,
            32 => Task::CashOut125,
            33 => Task::CashOut135,
            34 => Task::CashOut150,
            35 => Task::CashOut160,
            36 => Task::CashOut180,
            37 => Task::CashOut200,
            38 => Task::CashOut300,
            39 => Task::CashOut400,
            40 => Task::CashOut500,
            41 => Task::CashOut600,
            42 => Task::CashOut700,
            43 => Task::Harvest,
            44 => Task::Harvest5,
            45 => Task::Harvest40,
            46 => Task::Harvest80,
            47 => Task::Jackpot,
            48 => Task::Lunarian,
            49 => Task::Moonshot,
            50 => Task::LunarEclipse,
            51 => Task::Supernova,
            52 => Task::InfiniteGlitch,
            53 => Task::Survivor1,
            54 => Task::Survivor2,
            55 => Task::Linear,
            56 => Task::Exponential,
            57 => Task::Metagamer,
            58 => Task::Medic,
            59 => Task::Immortal,
            60 => Task::Immortal5,
            61 => Task::Armageddon3,
            62 => Task::Armageddon4,
            63 => Task::BombStreak3,
            64 => Task::BombStreak4,
            65 => Task::BombStreak5,
            66 => Task::FullyTorqued,
            67 => Task::GameBombs10,
            68 => Task::GameBombs15,
            69 => Task::Defused,
            70 => Task::Flatline,
            71 => Task::WhatNow,
            72 => Task::Loyalty,
            73 => Task::LevelReacher2,
            74 => Task::LevelReacher3,
            75 => Task::LevelReacher4,
            76 => Task::LevelReacher5,
            77 => Task::LevelReacher6,
            78 => Task::BagCopies4,
            79 => Task::BagCopies5,
            80 => Task::BagCopies6,
            81 => Task::BagSize20,
            82 => Task::BagSize25,
            83 => Task::BombPuller,
            84 => Task::HealthPuller,
            85 => Task::MultiplierPuller,
            86 => Task::OrbPuller,
            87 => Task::PointsPuller,
            88 => Task::SpecialPuller,
            _ => Task::None,
        }
    }
}
